name: VanillaTweaks
version: ${version}
main: me.machinemaker.vanillatweaks.VanillaTweaks
api-version: 1.17
authors:
  - Machine_Maker
description: A replacement for the VanillaTweaks datapack

permissions:
  vanillatweaks.admin:
    default: op
    description: All of the admin commands for all modules
    children:
      vanillatweaks.admin.grave-key: true

  vanillatweaks.afkdisplay:
    default: true
    description: Players will have afk status activated

  vanillatweaks.coordinateshud.togglehud:
    default: true
    description: Toggle HUD

  vanillatweaks.durabilityping.configure:
    default: true
    description: Ability to configure your personal durability ping
  vanillatweaks.durabilityping.toggle:
    default: true
    description: "Toggle durability ping notification (OUTDATED! use: `vanillatweaks.durabilityping.configure`"
    children:
      vanillatweaks.durabilityping.configure: true
  vanillatweaks.durabilityping:
    default: true
    description: Gets the durability notification
    children:
      vanillatweaks.durabilityping.toggle: true

  vanillatweaks.multiplayersleep.configure:
    default: true
    description: Ability to configure your personal multiplayer sleep notification
  vanillatweaks.multiplayersleep.list-sleeping:
    default: true
    description: List sleeping players

  vanillatweaks.graves:
    default: true
    description: Player death will spawn a grave
  vanillatweaks.graves.locate:
    default: true
    description: Use the graves locate command to find your last grave (requires grave locations to be toggled on in the configuration)
  vanillatweaks.playergraves:
    default: true
    description: (use vanillatweaks.graves)
    children:
      vanillatweaks.graves: true
  vanillatweaks.admin.grave-key:
    default: false
    description: Obtain and use a grave key to unlock any grave

  vanillatweaks.netherportalcoords:
    default: true
    description: Use /pcoords

  vanillatweaks.workstationhighlights.findworkstation:
    default: true
    description: Find villager workstations with /find-workstation

  vanillatweaks.realtimeclock.local:
    default: true
    description: Show game time for the current world
  vanillatweaks.realtimeclock.other:
    default: true
    description: Show game time for other worlds
  vanillatweaks.realtimeclock:
    default: true
    description: Show game time for the current world or a specific world
    children:
      vanillatweaks.realtimeclock.local: true
      vanillatweaks.realtimeclock.other: true

  vanillatweaks.wrench.redstone:
    default: true
    description: Use a wrench to rotate redstone components
  vanillatweaks.wrench.terracotta:
    default: true
    description: Use a wrench to rotate terracotta blocks

  vanillatweaks.spawn.current:
    default: false
    description: Use /spawn command (for current world)
  vanillatweaks.spawn.other:
    default: false
    description: Use /spawn command (for any world)
    children:
      vanillatweaks.spawn.current: true
  vanillatweaks.spawn:
    default: true
    description: Use /spawn command (both for current world and other worlds)
    children:
      vanillatweaks.spawn.current: true
      vanillatweaks.spawn.other: true

  vanillatweaks.killboats:
    default: op
    description: Use kill boats command

  vanillatweaks.largerphantoms:
    default: true
    description: Phantoms spawned on these players will be affected

  vanillatweaks.silencemobs:
    default: true
    description: Allow player to silence mobs

  vanillatweaks.villagerdeathmessages.death:
    default: true
    description: Get a message when a villager dies
  vanillatweaks.villagerdeathmessages.conversion:
    default: true
    description: Get a message when a villager converts
  vanillatweaks.villagerdeathmessages:
    default: true
    description: Get a message for either reason
    children:
      vanillatweaks.villagerdeathmessages.death: true
      vanillatweaks.villagerdeathmessages.conversion: true

  vanillatweaks.spectatortoggle:
    default: true
    description: Spectators can toggle both the Night Vision and Conduit Power effects
    children:
      vanillatweaks.spectatortoggle.nightvision: true
      vanillatweaks.spectatortoggle.conduitpower: true
  vanillatweaks.spectatortoggle.nightvision:
    default: true
    description: Spectators can toggle the Night Vision effect
  vanillatweaks.spectatortoggle.conduitpower:
    default: true
    description: Spectators can toggle the Conduit Power effect

  vanillatweaks.elevators.create:
    default: true
    description: Create elevators
  vanillatweaks.elevators.use:
    default: true
    description: Use elevators

  vanillatweaks.playerheaddrops:
    default: true
    description: Players killed by this player will drop heads

  vanillatweaks.mobdeathcount.help:
    default: false
    description: Use /mdc help
  vanillatweaks.mobdeathcount.start:
    default: false
    description: Use /mdc start
  vanillatweaks.mobdeathcount.stop:
    default: false
    description: Use /mdc stop
  vanillatweaks.mobdeathcount.reset:
    default: false
    description: Use /mdc reset
  vanillatweaks.mobdeathcount.toggle:
    default: false
    description: Use /mdc toggle
  vanillatweaks.mobdeathcount:
    default: true
    description: Use all /mdc commands
    children:
      vanillatweaks.mobdeathcount.help: true
      vanillatweaks.mobdeathcount.start: true
      vanillatweaks.mobdeathcount.stop: true
      vanillatweaks.mobdeathcount.reset: true
      vanillatweaks.mobdeathcount.toggle: true

  vanillatweaks.spawningspheres.add:
    default: false
    description: Use /ss add
  vanillatweaks.spawningspheres.remove:
    default: false
    description: Use /ss remove
  vanillatweaks.spawningspheres:
    default: op
    description: Use SpawningSpheres commands
    children:
      vanillatweaks.spawningspheres.add: true
      vanillatweaks.spawningspheres.remove: true

  vanillatweaks.trackrawstats.show:
    default: false
    description: Display a specific stat
  vanillatweaks.trackrawstats.clear:
    default: false
    description: Clear the sidebar
  vanillatweaks.trackrawstats:
    default: op
    description: All TrackRawStats commands
    children:
      vanillatweaks.trackrawstats.clear: true
      vanillatweaks.trackrawstats.show: true

  vanillatweaks.trackstats.show:
    default: false
    description: Display a specific processed stat
  vanillatweaks.trackstats.clear:
    default: false
    description: Clears the shown processed stat
  vanillatweaks.trackstats:
    default: op
    description: All TrackStats commands
    children:
      vanillatweaks.trackstats.show: true
      vanillatweaks.trackstats.clear: true

  vanillatweaks.homes.sethome:
    default: false
    description: Allow players to set homes
  vanillatweaks.homes.delhome:
    default: false
    description: Allow players to delete a home
  vanillatweaks.homes.list:
    default: false
    description: Allow players to list their homes
  vanillatweaks.homes.rename:
    default: false
    description: Allow players to rename their homes
  vanillatweaks.homes.home:
    default: false
    description: Allow players to teleport to their homes
  vanillatweaks.homes:
    default: true
    description: Allows all non-admin commands for the Homes module
    children:
      vanillatweaks.homes.sethome: true
      vanillatweaks.homes.delhome: true
      vanillatweaks.homes.list: true
      vanillatweaks.homes.rename: true
      vanillatweaks.homes.home: true

  vanillatweaks.pillagertools.config:
    default: op
    description: Configure PillagerTools in-game
  vanillatweaks.pillagertools.status:
    default: true
    description: View pillager tool settings

  vanillatweaks.tag.givetag:
    default: false
    description: Gives you or a player a tag
  vanillatweaks.tag.reset:
    default: false
    description: Resets a players it status
  vanillatweaks.tag.counter:
    default: false
    description: Sets the display slot for the tag counter
  vanillatweaks.tag.config:
    default: false
    description: Configure Tag in-game
  vanillatweaks.tag:
    default: op
    description: All tag commands
    children:
      vanillatweaks.tag.givetag: true
      vanillatweaks.tag.reset: true
      vanillatweaks.tag.counter: true
      vanillatweaks.tag.config: true

  vanillatweaks.thundershrine.create:
    default: false
    description: Create a Thunder Shrine
  vanillatweaks.thundershrine.remove:
    default: false
    description: Removes a Thunder Shrine
  vanillatweaks.thundershrine:
    default: true
    description: Thunder shrine commands
    children:
      vanillatweaks.thundershrine.remove: true
      vanillatweaks.thundershrine.create: true

  vanillatweaks.back:
    default: true
    description: Use the back command to return to previous locations
  vanillatweaks.back.config:
    default: op
    description: Configure Back in-game

  vanillatweaks.tpa.request:
    default: false
    description: Request to teleport to another player
  vanillatweaks.tpa.cancel:
    default: false
    description: Cancel your request to teleport to another player
  vanillatweaks.tpa.accept:
    default: false
    description: Accept another player's request to teleport to you
  vanillatweaks.tpa.deny:
    default: false
    description: Deny another player's request to teleport to you
  vanillatweaks.tpa.config:
    default: op
    description: Configure TPA in-game
  vanillatweaks.tpa:
    default: true
    children:
      vanillatweaks.tpa.request: true
      vanillatweaks.tpa.cancel: true
      vanillatweaks.tpa.accept: true
      vanillatweaks.tpa.deny: true

libraries:
  - com.google.inject:guice:5.0.1
  - com.google.inject.extensions:guice-assistedinject:5.0.1
  - io.github.classgraph:classgraph:4.8.114
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.5
  - io.leangen.geantyref:geantyref:1.3.11
  - org.apache.commons:commons-configuration2:2.7
  - commons-beanutils:commons-beanutils:1.9.4
  - org.jdbi:jdbi3-core:3.22.0
  - org.jdbi:jdbi3-sqlobject:3.22.0
  - com.h2database:h2:1.4.200
