name: PaperTweaks
version: ${version}
main: me.machinemaker.papertweaks.PaperTweaks
api-version: "1.20"
authors:
  - Machine_Maker
description: A replacement for the VanillaTweaks datapack

dependencies:
  server:
    WorldGuard:
      required: false
      join-classpath: true
    GriefPrevention:
      required: false
      join-classpath: true
    Multiverse-Core:
      load: BEFORE
      required: false
      join-classpath: false
    Hyperverse:
      load: BEFORE
      required: false
      join-classpath: false

permissions:
  # deprecated permissions
  vanillatweaks.admin.grave-key:
    default: false
    description: Deprecated, use vanillatweaks.graves.admin.grave-key
    children:
      vanillatweaks.graves.admin.grave-key: true

  vanillatweaks.admin:
    default: op
    description: All of the admin commands for all modules
    children:
      vanillatweaks.graves.admin: true
      vanillatweaks.killboats: true
      vanillatweaks.spawningspheres: true
      vanillatweaks.pillagertools.admin.config: true
      vanillatweaks.tag.admin.config: true
      vanillatweaks.wanderingtrades.admin.config: true
      vanillatweaks.tpa.admin.config: true
      vanillatweaks.back.admin.config: true
      vanillatweaks.multiplayersleep.admin.config: true
      vanillatweaks.durabilityping.admin.config: true

  vanillatweaks.main.enable:
    default: op
    description: Enable a module
  vanillatweaks.main.disable:
    default: op
    description: Disable a module
  vanillatweaks.main.reload:
    default: op
    description: Reload parts of the plugin
  vanillatweaks.main.list:
    default: true
    description: List enabled modules
  vanillatweaks.main.list.all:
    default: op
    description: List all modules
    children:
      vanillatweaks.main.list: true
  vanillatweaks.main.version:
    default: true
    description: Show version info

  vanillatweaks.afkdisplay:
    default: true
    description: Players will have afk status activated

  vanillatweaks.coordinateshud.togglehud:
    default: true
    description: Toggle HUD
  vanillatweaks.coordinateshud.togglehud.others:
    default: op
    description: Toggle HUD for other players

  vanillatweaks.durabilityping.config:
    default: true
    description: Ability to configure your personal durability ping
  vanillatweaks.durabilityping.notification:
    default: true
    description: Gets the durability notification
  vanillatweaks.durabilityping.admin.config:
    default: op
    description: Configure DurabilityPing in-game

  vanillatweaks.multiplayersleep.config:
    default: true
    description: Ability to configure your personal multiplayer sleep notification
  vanillatweaks.multiplayersleep.sleeping:
    default: true
    description: List sleeping players
  vanillatweaks.multiplayersleep.admin.config:
    default: op
    description: Configure MultiplayerSleep in-game

  vanillatweaks.graves:
    default: true
    description: Player death will spawn a grave
  vanillatweaks.graves.locate:
    default: true
    description: Use the graves locate command to find your last grave (requires grave locations to be toggled on in the configuration)
  # TODO remove this old perm at some point
  vanillatweaks.playergraves:
    default: true
    description: (use vanillatweaks.graves)
    children:
      vanillatweaks.graves: true
  vanillatweaks.graves.admin:
    default: op
    description: All of the admin commands for the graves module
    children:
      vanillatweaks.graves.admin.grave-key: true
      vanillatweaks.graves.admin.config: true
  vanillatweaks.graves.admin.grave-key:
    default: op
    description: Obtain and use a grave key to unlock any grave
  vanillatweaks.graves.admin.config:
    default: op
    description: Configure Graves in-game

  vanillatweaks.netherportalcoords:
    default: true
    description: Use /pcoords

  vanillatweaks.workstationhighlights.findworkstation:
    default: true
    description: Find villager workstations with /find-workstation

  vanillatweaks.realtimeclock.local:
    default: true
    description: Show game time for the current world
  vanillatweaks.realtimeclock.other:
    default: true
    description: Show game time for other worlds
  vanillatweaks.realtimeclock:
    default: true
    description: Show game time for the current world or a specific world
    children:
      vanillatweaks.realtimeclock.local: true
      vanillatweaks.realtimeclock.other: true

  vanillatweaks.wrench.redstone:
    default: true
    description: Use a wrench to rotate redstone components
  vanillatweaks.wrench.terracotta:
    default: true
    description: Use a wrench to rotate terracotta blocks

  vanillatweaks.spawn.current:
    default: false
    description: Use /spawn command (for current world)
  vanillatweaks.spawn.other:
    default: false
    description: Use /spawn command (for any world)
  vanillatweaks.spawn:
    default: true
    description: Use /spawn command (both for current world and other worlds)
    children:
      vanillatweaks.spawn.current: true
      vanillatweaks.spawn.other: true

  vanillatweaks.killboats:
    default: op
    description: Use kill boats command

  vanillatweaks.largerphantoms:
    default: true
    description: Phantoms spawned on these players will be affected

  vanillatweaks.silencemobs:
    default: true
    description: Allow player to silence mobs

  vanillatweaks.villagerdeathmessages.death:
    default: true
    description: Get a message when a villager dies
  vanillatweaks.villagerdeathmessages.conversion:
    default: true
    description: Get a message when a villager converts
  vanillatweaks.villagerdeathmessages:
    default: true
    description: Get a message for either reason
    children:
      vanillatweaks.villagerdeathmessages.death: true
      vanillatweaks.villagerdeathmessages.conversion: true

  vanillatweaks.spectatortoggle:
    default: true
    description: Spectators can toggle both the Night Vision and Conduit Power effects
    children:
      vanillatweaks.spectatortoggle.nightvision: true
      vanillatweaks.spectatortoggle.conduitpower: true
  vanillatweaks.spectatortoggle.nightvision:
    default: true
    description: Spectators can toggle the Night Vision effect
  vanillatweaks.spectatortoggle.conduitpower:
    default: true
    description: Spectators can toggle the Conduit Power effect

  vanillatweaks.elevators.create:
    default: true
    description: Create elevators
  vanillatweaks.elevators.use:
    default: true
    description: Use elevators

  vanillatweaks.playerheaddrops:
    default: true
    description: Players killed by this player will drop heads
  vanillatweaks.playerheaddrops.admin.config:
    default: op
    description: Configure PlayerHeadDrops in-game

  vanillatweaks.mobdeathcount.start:
    default: false
    description: Use /mdc start
  vanillatweaks.mobdeathcount.stop:
    default: false
    description: Use /mdc stop
  vanillatweaks.mobdeathcount.reset:
    default: false
    description: Use /mdc reset
  vanillatweaks.mobdeathcount.toggle:
    default: false
    description: Use /mdc toggle
  vanillatweaks.mobdeathcount:
    default: true
    description: Use all /mdc commands
    children:
      vanillatweaks.mobdeathcount.start: true
      vanillatweaks.mobdeathcount.stop: true
      vanillatweaks.mobdeathcount.reset: true
      vanillatweaks.mobdeathcount.toggle: true

  vanillatweaks.spawningspheres.add:
    default: false
    description: Use /ss add
  vanillatweaks.spawningspheres.remove:
    default: false
    description: Use /ss remove
  vanillatweaks.spawningspheres:
    default: op
    description: Use SpawningSpheres commands
    children:
      vanillatweaks.spawningspheres.add: true
      vanillatweaks.spawningspheres.remove: true

  vanillatweaks.trackrawstats.display:
    default: false
    description: Display a specific stat
  vanillatweaks.trackrawstats.clear:
    default: false
    description: Clear the sidebar
  vanillatweaks.trackrawstats:
    default: op
    description: All TrackRawStats commands
    children:
      vanillatweaks.trackrawstats.display: true
      vanillatweaks.trackrawstats.clear: true

  vanillatweaks.trackstats.show:
    default: false
    description: Display a specific processed stat
  vanillatweaks.trackstats.clear:
    default: false
    description: Clears the shown processed stat
  vanillatweaks.trackstats:
    default: op
    description: All TrackStats commands
    children:
      vanillatweaks.trackstats.show: true
      vanillatweaks.trackstats.clear: true

  vanillatweaks.homes.sethome:
    default: false
    description: Allow players to set homes
  vanillatweaks.homes.delhome:
    default: false
    description: Allow players to delete a home
  vanillatweaks.homes.list:
    default: false
    description: Allow players to list their homes
  vanillatweaks.homes.rename:
    default: false
    description: Allow players to rename their homes
  vanillatweaks.homes.home:
    default: false
    description: Allow players to teleport to their homes
  vanillatweaks.homes:
    default: true
    description: Allows all non-admin commands for the Homes module
    children:
      vanillatweaks.homes.sethome: true
      vanillatweaks.homes.delhome: true
      vanillatweaks.homes.list: true
      vanillatweaks.homes.rename: true
      vanillatweaks.homes.home: true

  vanillatweaks.pillagertools.admin.config:
    default: op
    description: Configure PillagerTools in-game
  vanillatweaks.pillagertools.status:
    default: true
    description: View pillager tool settings

  vanillatweaks.tag.givetag:
    default: false
    description: Gives you or a player a tag
  vanillatweaks.tag.reset:
    default: false
    description: Resets a players it status
  vanillatweaks.tag.counter:
    default: false
    description: Sets the display slot for the tag counter
  vanillatweaks.tag.admin.config:
    default: false
    description: Configure Tag in-game
  vanillatweaks.tag:
    default: op
    description: All tag commands
    children:
      vanillatweaks.tag.givetag: true
      vanillatweaks.tag.reset: true
      vanillatweaks.tag.counter: true
      vanillatweaks.tag.admin.config: true

  vanillatweaks.thundershrine.create:
    default: false
    description: Create a Thunder Shrine
  vanillatweaks.thundershrine.remove:
    default: false
    description: Removes a Thunder Shrine
  vanillatweaks.thundershrine:
    default: true
    description: Thunder shrine commands
    children:
      vanillatweaks.thundershrine.remove: true
      vanillatweaks.thundershrine.create: true

  vanillatweaks.back:
    default: true
    description: Use the back command to return to previous locations
  vanillatweaks.back.admin.config:
    default: op
    description: Configure Back in-game

  vanillatweaks.tpa.request:
    default: false
    description: Request to teleport to another player
  vanillatweaks.tpa.cancel:
    default: false
    description: Cancel your request to teleport to another player
  vanillatweaks.tpa.accept:
    default: false
    description: Accept another player's request to teleport to you
  vanillatweaks.tpa.deny:
    default: false
    description: Deny another player's request to teleport to you
  vanillatweaks.tpa.admin.config:
    default: op
    description: Configure TPA in-game
  vanillatweaks.tpa:
    default: true
    children:
      vanillatweaks.tpa.request: true
      vanillatweaks.tpa.cancel: true
      vanillatweaks.tpa.accept: true
      vanillatweaks.tpa.deny: true

  vanillatweaks.wanderingtrades.admin.config:
    default: op
    description: Configure WanderingTrades in-game

  vanillatweaks.moremobheads:
    default: true
    description: Mobs killed by this player will drop heads (if killed by a player)
  vanillatweaks.moremobheads.admin.config:
    default: op
    description: Configure MoreMobHeads in-game

  vanillatweaks.treasuregems.give:
    default: op
    description: Give yourself the gem micro blocks from treasure gems

  vanillatweaks.gemvillagers.spawn:
    default: op
    description: Spawn a new gem villager

  vanillatweaks.armoredelytra.create:
    default: false
    description: Allows creating the elytra (applies to the player that dropped the first item)
  vanillatweaks.armoredelytra.destroy:
    default: false
    description: Allows destroying the armored elytra (applies to the player that dropped it)
  vanillatweaks.armoredelytra:
    default: true
    description: Allows creating and destruction of the elytra
    children:
      vanillatweaks.armoredelytra.create: true
      vanillatweaks.armoredelytra.destroy: true
