name: VanillaTweaks
version: ${version}
main: me.machinemaker.vanillatweaks.VanillaTweaks
api-version: 1.16
authors: [ Machine_Maker ]
description: A replacement for the VanillaTweaks datapack

permissions:

  vanillatweaks.mobdrops.doubleshulkershells:
    default: true
    description: Shulkers killed by this player will be affected
  vanillatweaks.mobdrops.dragondrops:
    default: true
    description: Dragons killed by this player will be affected
  vanillatweaks.mobdrops:
    default: true
    description: Entities killed by this player will be affected
    children:
      vanillatweaks.mobdrops.doubleshulkershells: true
      vanillatweaks.mobdrops.dragondrops: true
  vanillatweaks.moremobheads:
    default: true
    description: Mobs killed by this player will drop heads (if killed by a player)
  vanillatweaks.pillagertools:
    default: op
    description: Use both commands
    children:
      vanillatweaks.pillagertools.toggle: true
      vanillatweaks.pillagertools.status: true
  vanillatweaks.tag.givetag:
    default: op
    description: Gives you or a player a tag
  vanillatweaks.tag.reset:
    default: op
    description: Resets a players it status
  vanillatweaks.tag:
    default: op
    description: All tag commands
    children:
      vanillatweaks.tag.givetag: true
      vanillatweaks.tag.reset: true
  vanillatweaks.thundershrine.create:
    default: true
    description: Create a Thunder Shrine
  vanillatweaks.thundershrine.remove:
    default: true
    description: Removes a Thunder Shrine
  vanillatweaks.thundershrine.help:
    default: true
    description: Thunder Shrine help command
  vanillatweaks.thundershrine:
    default: true
    description: Thunder shrine commands
    children:
      vanillatweaks.thundershrine.remove: true
      vanillatweaks.thundershrine.create: true
      vanillatweaks.thundershrine.help: true
