name: VanillaTweaks
version: ${version}
main: me.machinemaker.vanillatweaks.VanillaTweaks
api-version: 1.16
authors: [ Machine_Maker ]
description: A replacement for the VanillaTweaks datapack

permissions:
  vanillatweaks.moremobheads:
    default: true
    description: Mobs killed by this player will drop heads (if killed by a player)
